---
#
# Ansible managed
#
repository:
  description: Install and configure php on your system.
  homepage: https://buluma.github.io/
  topics: installer, package, php, web, ansible, molecule, tox, playbook, hacktoberfest
