---
#
# Ansible managed
#

name: Release to Ansible Galaxy

on:
  release:
    types: [created, edited, published, released]

# TODO: add to tracker
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: galaxy
        uses: buluma/galaxy-action@v1.0.3
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          git_branch: master
